name: Test Build Docker containers

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

jobs:
  tps-tick:
    name:                         Build tps (tick) image
    runs-on:                      ubuntu-latest
    steps:
      - name: Checkout Code
        uses:                       actions/checkout@v3
      - name: Build image
        run: |
          CHAIN=tick
          VCS_REF=${{ github.ref }}
          BUILD_DATE=${{ github.event.release.published_at }}
          docker build -f utils/dockerfiles/Dockerfile.tps --build-arg CHAIN=$CHAIN --build-arg VCS_REF=$VCS_REF --build-arg BUILD_DATE=$BUILD_DATE -t stps-tps:versi-tick-latest .
